analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.5
  rhythmicContrast: 0.755924
  saturation: 0.311936
cta: {}
layout_spectrum: 0.532657
name: Solar Planet
opengraph: {}
purpose: []
typography_spectrum: 0.834459
