analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.5
  rhythmicContrast: 0.7559248660691082
  saturation: 0.15384097979404032
cta: {}
layout_spectrum: 0.031531
name: Solar Planet
opengraph: {}
purpose: []
typography_spectrum: 0.75636
